title: 최성진
description: 안드로이드 앱 개발자
site_title: '최성진 - 포트폴리오'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# GitHub Pages 설정
repository: Sungjincc/Sungjincc.github.io
url: "https://Sungjincc.github.io"
baseurl: ""

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude: 
  - vendor/ruby
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

# Personalization
github_username: Sungjincc
blog_url: https://Sungjincc.github.io/
email: chltjdwls294@naver.com
keybase_username: 최성진
twitter_username: 최성진
reddit_username: 최성진

# absolute or relative
profile_picture: assets/images/sungjin.jpg

# Google Analytics ID
google_analytics: 
